### PR TITLE
Depend on vm_service 6.0.1-nullsafety.1

### PR DESCRIPTION
**Pull request by grouma**

### CODE REVIEW

**Review by bkonyi — APPROVED** [review]

**Comment by dnfield** [comment]
This will need a publish to be able to roll vm_service into flutter.

Have we verified whether the vm_service changes fix debuggers?

**Comment by grouma** [comment]
Published. Verified that it resolves Dart DevTool issues. The IDE debuggers use the same API so they should be fixed as well.

**Comment by dnfield** [comment]
Is there a test we can add to vm_service to avoid this regression in the future? @bkonyi ?

**Comment by bkonyi** [comment]
I think the right thing to do (eventually) is to port all the tests under `runtime/observatory/tests/service/` to `pkg/vm_service/tests`. Once we unfork the tests in the SDK, I'm going to start porting and refactoring those tests to the `package:vm_service` test suite.

**Pull request merged**
