### PR TITLE
Update _fe_analyzer_shared to version ^38.0.0

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/dart-lang/webdev/issues/1572.

This unblocks flutter's quest to enable super parameters (https://github.com/flutter/flutter/issues/100575).

### CODE REVIEW

**Review by bkonyi — APPROVED** [review]

**Comment by goderbauer** [comment]
@annagrin or @elliette Any chance you could publish a release with this change to pub to unblock Flutter? Thanks!

**Comment by elliette** [comment]
Hi @goderbauer - sure! Is it okay if the release waits until early next week? I'm always hesitant to do release on a Friday afternoon 😬

**Comment by goderbauer** [comment]
> Is it okay if the release waits until early next week? I'm always hesitant to do release on a Friday afternoon 😬

Early next week is totally fine! Thanks!

**Comment by annagrin** [comment]
Published version 13.1.0: 
- https://github.com/dart-lang/webdev/releases/tag/dwds-v13.1.0
- https://pub.dev/packages/dwds

**Comment by goderbauer** [comment]
Thank you!

**Pull request merged**
