### PR TITLE
update example

### PR DESCRIPTION
**Pull request by kevmoo**
- Support the latest dependencies
- update example

### CODE REVIEW

**Review by grouma — COMMENTED** [review]
Should we wait for https://github.com/dart-lang/webdev/pull/1351 to land?

**Comment by kevmoo** [comment]
> Should we wait for #1351 to land?

Yup! This is a follow-up

**Comment by kevmoo** [comment]
...should have marked it as a draft, sorry!

**Review by natebosch — APPROVED** [review]

**Comment by kevmoo** [comment]
Landing on red CI – due to dwds

**Pull request merged**
