### PR TITLE
Prep to publish

### PR DESCRIPTION
**Pull request by grouma**

### CODE REVIEW

**Comment by grouma** [comment]
cc @jonahwilliams

**Review by annagrin — APPROVED** [review]
Apologies, I missed that one - should we include new fixes as well?

**Comment by grouma** [comment]
> Apologies, I missed that one - should we include new fixes as well?

Yeah I'll rebase.

**Comment by grouma** [comment]
Closing in favor of https://github.com/dart-lang/webdev/pull/1309

**Pull request closed without merging**
