### PR TITLE
Update README.md to use `dart pub` instead of `pub`

### PR DESCRIPTION
**Pull request by julemand101**
The `pub` command no longer exist and users are therefore required to use `dart pub` instead for installation.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by elliette** [comment]
Thanks! The failing release reminder test should be fixed by merging this branch with master

**Comment by julemand101** [comment]
Hope I done the pull correctly and everything is okay now.

**Comment by elliette** [comment]
Thank you! LGTM

**Comment by julemand101** [comment]
@elliette Do you know why this pull-request have yet to be merged? It does not really have any kind of deadline but I just find it weird it just stays in this state like it is waiting for something?

**Comment by elliette** [comment]
> auto label is removed for dart-lang/webdev/2195, due to This PR has not met approval requirements for merging. You are not a member of dart-team and need 1 more review(s) in order to merge this PR.

You will need to merge it manually (with the Squash and merge button) - if you don't see it, I can merge it for you.

**Comment by julemand101** [comment]
Well, I don't have that button so you are allowed to do so for me :)
Guess it is because I am not part of the project?

**Pull request merged**
