### PR TITLE
[WIP] Verify vm protocol objects

### PR DESCRIPTION
**Pull request by grouma**
Closes https://github.com/dart-lang/webdev/issues/586

### CODE REVIEW

**Comment by jakemac53** [comment]
We should really update the actual vm service package to have these constructors imo - this is fine for now to unblock but it will not keep up to date with the spec as it changes.

**Comment by devoncarew** [comment]
> We should really update the actual vm service package to have these constructors imo

I agree - package:vm_service is pretty easy to work on, and I'm sure would be totally open to these kinds of changes (additional constructors or similar). cc @bkonyi

**Comment by devoncarew** [comment]
https://github.com/dart-lang/sdk/tree/master/pkg/vm_service

@bkonyi, we may want to add a brief doc there to provide guidance about how to contribute - that the code in lib/ is largely generated, how to run the generator, ...

**Comment by bkonyi** [comment]
> > We should really update the actual vm service package to have these constructors imo
> 
> I agree - package:vm_service is pretty easy to work on, and I'm sure would be totally open to these kinds of changes (additional constructors or similar). cc @bkonyi

I totally agree. No sense in wrapping package:vm_service for functionality that isn't product specific.

**Comment by bkonyi** [comment]
> https://github.com/dart-lang/sdk/tree/master/pkg/vm_service
> 
> @bkonyi, we may want to add a brief doc there to provide guidance about how to contribute - that the code in lib/ is largely generated, how to run the generator, ...

SGTM.

**Comment by grouma** [comment]
Opened this for tracking: https://github.com/dart-lang/sdk/issues/38194

**Pull request merged**
