### PR TITLE
[MV3] Dart debug extension supports DWDS versions < `17.0.0`

### PR DESCRIPTION
**Pull request by elliette**
We are now relying on `DebugInfo` being sent along with the `dart-app-ready` event. This will be included as part of the `17.0.0` of DWDS. 

For backwards compatibility with older versions of DWDS, this PR adds the ability to read the `DebugInfo` directly off of the `Window` object instead if it's missing from the `dart-app-ready` event.

### CODE REVIEW

**Review by annagrin — COMMENTED** [review]
Can we test this?

**Comment by elliette** [comment]
> Can we test this?

We can't currently test this because we are always testing everything against DWDS master, and this is only needed for older versions of DWDS. I think it will require a fair amount of work to get testing for this change, including splitting the debug extension out of DWDS, and not depending on DWDS test infrastructure to run out tests.

**Comment by elliette** [comment]
> > Can we test this?
> 
> We can't currently test this because we are always testing everything against DWDS master, and this is only needed for older versions of DWDS. I think it will require a fair amount of work to get testing for this change, including splitting the debug extension out of DWDS, and not depending on DWDS test infrastructure to run out tests.

Actually, figured out how to add a simple test!

**Review by annagrin — APPROVED** [review]
LGTM!

**Pull request merged**
