### PR TITLE
Fix TestSdkConfigurationProvider.dispose

### PR DESCRIPTION
**Pull request by derekxu16**
CI was hanging on my PR (https://github.com/dart-lang/webdev/actions/runs/7224561961/job/19690368821?pr=2307) and it looks like this change will fix it.

### CODE REVIEW

**Comment by annagrin** [comment]
Thanks Derek, could you please update the changelog (see other PRs for examples)?

**Comment by derekxu16** [comment]
Which changelog should I update? `package:test_common` doesn't have one.

**Comment by annagrin** [comment]
Ah, sorry, this is just for tests - I'll add a label to skip the changelog verification

**Review by annagrin — APPROVED** [review]
LGTM!

**Pull request merged**
