### PR TITLE
Remove unused deps and rev build_daemon version

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Oops!

**Comment by kevmoo** [comment]
Feel free to rebase and merge and delete the branch if you're happy

**Comment by kevmoo** [comment]
'twas keeping us from getting the last build deps

**Comment by jakemac53** [comment]
I think @grouma was going to update the build_daemon version already, going to leave this up to him as he has more context.

Please rename the PR though now that it doesn't accurately describe the change.

**Comment by kevmoo** [comment]
> I think @grouma was going to update the build_daemon version already, going to leave this up to him as he has more context.
> 
> Please rename the PR though now that it doesn't accurately describe the change.

Interesting story: by dropping the dep, it breaks things in such a way that I HAD to bump `duild_daemon`.

So I can wait for @grouma here – whatever he likes

**Comment by grouma** [comment]
LGTM. Prepped it for release.

**Comment by jakemac53** [comment]
`built_value_generator` is actually needed for codegen...

**Comment by kevmoo** [comment]
Wha? Oh crap...I didn't see a usage.

...but it's in the builder!

Ugh. Sorry!

Back to waiting on https://github.com/google/built_value.dart/pull/639

**Pull request merged**
