### PR TITLE
Update SDK constraint everywhere

### PR DESCRIPTION
**Pull request by elliette**

### CODE REVIEW

**Review by annagrin — APPROVED** [review]
LGTM!

**Comment by kevmoo** [comment]
Is this required? I thought everything was opted-in to v3 by default?

CC @mit-mit @devoncarew

**Comment by mit-mit** [comment]
No, this is *not* required, see the 'Backwards compatibility for null safe packages' section in https://github.com/dart-lang/sdk/issues/49530 

Given it's a no-op, I'd recommend not churning all our packages for it. I'd recommend changing the upper constraint to `<4.0.0` when you get to the point when you are also changing the lower constraint to `>=3.0.0`.

**Comment by elliette** [comment]
> No, this is _not_ required, see the 'Backwards compatibility for null safe packages' section in [dart-lang/sdk#49530](https://github.com/dart-lang/sdk/issues/49530)
> 
> Given it's a no-op, I'd recommend not churning all our packages for it. I'd recommend changing the upper constraint to `<4.0.0` when you get to the point when you are also changing the lower constraint to `>=3.0.0`.

Got it, thank you! Closing in favor of https://github.com/dart-lang/webdev/pull/1817 (still a WIP) to fix the tests that are failing at head.

**Pull request closed without merging**
