### PR TITLE
format with the latest sdk

### PR DESCRIPTION
**Pull request by jakemac53**
Feel free to land on approval

### CODE REVIEW

**Comment by jakemac53** [comment]
cc @annagrin I am seeing a bunch of existing failures here for eval tests, looks like they have been failing for about a month?

**Review by kevmoo — APPROVED** [review]

**Comment by jakemac53** [comment]
I went ahead and merged since these failures are pre-existing

**Comment by annagrin** [comment]
> I am seeing a bunch of existing failures here for eval tests, looks like they have been failing for about a month?

I've been working on it for a while, I thought I managed to fix the issue in the SDK but looks like it is still happening...

**Comment by jakemac53** [comment]
Ok! Just wanted to make sure you were aware

**Comment by annagrin** [comment]
@kevmoo I am seeing this message on failures:

ERROR - 2021-07-12 15:35:00.321105
HEAD /hello_world/main.unsound.ddc.full.dill
Error thrown by handler.

package:shelf/shelf_io.dart 114:16  handleRequest

That seems to be the end of the stack trace. We use shelf and cascade that eventually handles requests from expression compiler worker by the build runner asset server. Do you have any hints on how to get more information on where exactly this is thrown?

**Pull request merged**
