### PR TITLE
Ensure pub/dart invoked by tests are the same as the top-level SDK

### PR DESCRIPTION
**Pull request by kevmoo**
Closes https://github.com/dart-lang/webdev/issues/23

### CODE REVIEW

**Comment by kevmoo** [comment]
I could imagine a LOT of head scratching trying to debug something w/ a mismatch here...

**Comment by kevmoo** [comment]
...something like this ought to be a package

Would it make sense to have this functionality in pkg:io or something?

**Comment by natebosch** [comment]
> Would it make sense to have this functionality in pkg:io or something?

It's already in cli_util. This logic also doesn't work internally.

**Comment by kevmoo** [comment]
> This logic also doesn't work internally.

Well, it's less broken in more places w/ this at least...

**Pull request merged**
