### PR TITLE
Fix failures due to cached items in build web directory

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by grouma** [comment]
This isn't really a fix. This is hiding the problem. We need https://github.com/dart-lang/build/pull/1994

**Comment by kevmoo** [comment]
Cool. We can skip the test in the meantime? Open to suggestions...

**Comment by grouma** [comment]
No need. I won't submit https://github.com/dart-lang/webdev/pull/101 until Travis is green. Just waiting on https://github.com/dart-lang/build/pull/1994 and a publish.

**Comment by kevmoo** [comment]
closing out. Fixed in build_runner

**Pull request closed without merging**
