### PR TITLE
Include static member information for classes

### PR DESCRIPTION
**Pull request by elliette**
Work towards https://github.com/dart-lang/webdev/issues/1430

Include static member information for classes now that DDC is exposing static member names (see https://github.com/dart-lang/sdk/commit/cc9353ac46be41ab1bfd4b56f33d92d3ab5ad8e8).

### CODE REVIEW

**Comment by elliette** [comment]
Hi @nshahan  - is there a way to tell if your [change](https://dart-review.googlesource.com/c/sdk/+/217501) is on stable or not? I'm wondering if that's why we're seeing the failing tests. If that's the case, it might make sense to pin the Dart SDK to the version your change is on.

**Review by annagrin — APPROVED** [review]
Thanks Elliott!

**Review by annagrin — COMMENTED** [review]
Could you please add the description of the change to dwds/CHANGELOG.md?

**Comment by nshahan** [comment]
> is there a way to tell if your change is on stable or not?

It has not been published in a stable release yet. It looks like it is present in the current beta starting at version 2.15.0-268.18.beta so it should be part of the next stable release.

**Comment by annagrin** [comment]
> > is there a way to tell if your change is on stable or not?

> It has not been published in a stable release yet. It looks like it is present in the current beta starting at version 2.15.0-268.18.beta so it should be part of the next stable release.

@elliette you can just disable the tests for anything below the version @nshahan mentioned, here is an example:
https://github.com/dart-lang/webdev/blob/8033d676a87f0bc80ba728c89c1fb86db3cf8cfc/webdev/test/e2e_test.dart#L159

**Comment by annagrin** [comment]
Merging so we can include the change in the next dwds version.

**Pull request merged**
