### PR TITLE
build_cli fun

### PR DESCRIPTION
**Pull request by kevmoo**
@grouma @jakemac53 – an idea...

### CODE REVIEW

**Comment by natebosch** [comment]
What is the improvement?

**Comment by kevmoo** [comment]
> What is the improvement?

Experimenting. In theory less hand managing arg names, conversions, casting, etc.

**Comment by jakemac53** [comment]
I don't feel strongly here, there isn't a ton of value provided for the `SharedOptions` case at least. I am curious how well this can compose though... can the `Configuration` class extend the `SharedOptions` class and not have to duplicate all those fields? With the available generated helpers right now it seems like it would have to be a separate object.

**Comment by grouma** [comment]
I'm not a huge fan of the `SharedOptions`. I don't think it provides any value. The build script on the other hand seems useful. We should include the injected client code in the script as well.

**Comment by kevmoo** [comment]
You have no seen my FYI. If you think `build_cli` is useful for this project or others, let me know!

**Pull request closed without merging**
