### PR TITLE
fix the example frontend server web app

### PR DESCRIPTION
**Pull request by jakemac53**
Fixes https://github.com/dart-lang/webdev/issues/1546

There are definitely some hacky-ish things here in terms of the routing, but it works and that isn't the focus of the example.

### CODE REVIEW

**Review by annagrin — COMMENTED** [review]
Thanks Jake! Is there an existing test that makes sure the example is working btw? If not, would it be possible to add it?

**Comment by jakemac53** [comment]
I added some basic tests, also fixed an issue with the vm client example

**Comment by jakemac53** [comment]
cc @johnniwinther do you have any insight into the error I am seeing? I can't repro it locally...

```
 [e] APP -> Unhandled exception:
  [e] APP -> 'org-dartlang-root:///example/app/main.dart': error: Unexpected tag 51 (AwaitExpression) in ::.main, expected expression
  [e] APP -> #0      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
  [e] APP -> #1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

This is coming from an app that is spawned by a precompiled dill (from frontend server).

**Comment by jakemac53** [comment]
For now I am just skipping the example vm client test, not sure why its failing on github actions.

**Comment by alexmarkov** [comment]
@johnniwinther Yes, this looks like an incompatibility between kernel binary (probably because the new front-end server is used in the tests) and the old Dart VM. We do not have any compatibility guarantees, which means that versions of front-end server and Dart VM should match exactly (should come from the same commit). These tests seem to violate this requirement.

**Comment by jakemac53** [comment]
I am not sure how these could be different versions... there is only one version of the Dart SDK downloaded in the job...

**Comment by alexmarkov** [comment]
It looks like the test doesn't perform any cleanup before/after running and doesn't check for errors.
Maybe front-end server compilation fails and test attempts to run stale and incompatible dill file `.dart_tool/out/example_app.dill`.

**Comment by jakemac53** [comment]
> It looks like the test doesn't perform any cleanup before/after running and doesn't check for errors.
> Maybe front-end server compilation fails and test attempts to run stale and incompatible dill file `.dart_tool/out/example_app.dill`.

I tried adding some cleanup to the examples themselves, we can see if that gives a different error. I didn't see any errors in the compile output though.

**Comment by jakemac53** [comment]
@alexmarkov thanks that did seem to fix it! I am not sure exactly what was happening still... each test should have overwritten the existing files from the previous test? Maybe frontend_server was appending instead?

**Comment by jakemac53** [comment]
Actually I wonder if it was picking up the previous dill file and doing an "incremental" compile or something, but from a dill compiled for the wrong platform?

**Review by annagrin — APPROVED** [review]
LGTM!

**Pull request merged**
