### PR TITLE
return RPCError.kMethodNotFound from unimplemented methods

### PR DESCRIPTION
**Pull request by devoncarew**
- return RPCError.kMethodNotFound from unimplemented methods
- fix https://github.com/dart-lang/webdev/issues/781

### CODE REVIEW

**Comment by natebosch** [comment]
Is there another level we could implement this at? Can the place where we hook up the service implementation to the wire catch the error and translate to the appropriate RPC error? Is `ChromeProxyService` already tied to the "RPC" concept?

**Comment by grouma** [comment]
> Is there another level we could implement this at? Can the place where we hook up the service implementation to the wire catch the error and translate to the appropriate RPC error? Is ChromeProxyService already tied to the "RPC" concept?

I believe that logic is actually handled by `package:vm_service` as we simply [pass](https://github.com/dart-lang/webdev/blob/0aa8026801344196a437c220f03f833d69a492cf/dwds/lib/src/services/debug_service.dart#L54) a `VmServiceInterface` to a `VmServerConnection` which are abstractions provided by that package.

**Comment by devoncarew** [comment]
> Is there another level we could implement this at? Can the place where we hook up the service implementation to the wire catch the error and translate to the appropriate RPC error?

I think this is the right layer. We should be returning the expected RPC objects here - both the normal RPC results, and the appropriate RPC error condition results.

The layer above will handle any unexpected exception and translate that into an unknown server error / RPCError.kInternalError.

> Is `ChromeProxyService` already tied to the "RPC" concept?

It is - it's the layer that's implementing the RPC calls.

**Comment by natebosch** [comment]
> It is - it's the layer that's implementing the RPC calls.

Not a great design RPC should be a communication/wireformat concern not an implemetnation concern, but if it's what the package we're using wants we should go with it.

Thanks!

**Comment by grouma** [comment]
Why was this merged on red?

**Comment by devoncarew** [comment]
> Why was this merged on red?

Hmm, I don't normally - I didn't see the travis status. Not sure if I didn't notice it or it wasn't written back to this PR properly.

**Pull request merged**
